declare module "async-ffmetadata"
declare interface metadataObj{
  /**title?: string,
  author?: string,
  album_artist?: string,
  album?: string,
  grouping?: string,
  composer?: string,
  year?: string,
  track?: string,
  comment?: string,
  genre?: string,
  copyright?: string,
  description?: string,
  synopsis?: string,
  show?: string,
  episode_id?: string,
  lyrics?: string,
  network?: string,
  disc?: string,
  publisher?: string,
  performer?: string,
  language?: string,
  encoder?: string,
  compilation?: string,
  date?: string,
  creation_time?: string,
  albumSort?: string,
  artistSort?: string,
  titleSort?: string,
  albumArtist?: string,**/
  [key: string]: string,
}
declare function getMetaDataFromFile(filePath:string): Promise<metadataObj>
declare function setMetaDataToFile(metaData: metadataObj, inFilePath: string, outFilePath: string): Promise<boolean>